#cloud-config

repo_update: true
repo_upgrade: security
write_files:
  - path: /etc/yum.repos.d/nginx.repo
    owner: root
    permissions: 0644
    content: |
      [nginx-stable]
      name=nginx stable repo
      baseurl=http://nginx.org/packages/centos/7/$basearch/
      gpgcheck=1
      enabled=1
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true

      [nginx-mainline]
      name=nginx mainline repo
      baseurl=http://nginx.org/packages/mainline/centos/7/$basearch/
      gpgcheck=1
      enabled=0
      gpgkey=https://nginx.org/keys/nginx_signing.key
      module_hotfixes=true
power_state:
  delay: "+10"
  mode: reboot
  message: Bye Bye
  timeout: 30
runcmd:
  - setenforce 0
  - sed -ie 's/^\SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
  - systemctl stop firewalld
  - systemctl disable firewalld
  - systemctl restart rsyslog
  - yum install -y nginx
  - systemctl start nginx
  - systemctl enable nginx

